#include <string>
#include <array>

const std::array<std::wstring, 45> Passwords = {
    L"ONCEUPONA", L"TIMETHEREWERE", L"SOMESMALLWORMS", L"WHOGOTVERYVERY", L"ANNOYEDAND",
    L"DECIDEDTO", L"GOTOARMSIN", L"ORDERTOWIPE", L"OUTTHEIR", L"VICIOUSENEMY",
    L"COUNTERPARTS", L"THEYDEVELOPED", L"SOMEREALLY", L"COOLWEAPONSSUCH", L"ASBANANABOMBS",
    L"ANDMAGICBULLETS", L"THEYTRAINED", L"ALLNIGHTAND", L"EVERYDAYSOTHEY", L"WOULDBECOME",
    L"PROFICIENT", L"INTHEIRWORMLY", L"WAYSSOMETIMES", L"THEYWOULDSHOOT", L"GRANNIESJUST",
    L"FORFUNANDLAUGH", L"ABOUTITINTHE", L"EVENINGTIME", L"WEAPOLOGISEON", L"BEHALFOFALLTHE",
    L"TERRITORIESTHAT", L"WEWENTTOTHE", L"TROUBLEOFTRANSLATING", L"WORMS2INTOBUTWE", L"DIDNTHAVETIMETO",
    L"TRANSLATETHESE", L"PASSWORDSNOTTHAT", L"THEYNEEDTOBEDONE", L"WESUPPOSETHAT", L"YOUAREREALLY",
    L"EXPECTINGTO", L"SEEAWONDERFUL", L"CHEATMODEWHEN", L"FINISHTHEMISSIONS", L"ANDYOUARERIGHT"
};